name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Behave Tests
        uses: cryptic-wizard/run-behave-tests@v0.3.0


          
     
