name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: is chrome install
      run: print(google-chrome --version)




      

      
    
    

    
    
     
