name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Chrome
      run: |
        brew reinstall --cask google-chrome
        /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version    
        
    - name: Checkout Chromedriver 
      run: |
          cd webdrivers/mac
          chromeDriver -v   
      
    - name: Add chromedriver to PATH
      run: |
          echo 'export PATH="/webdrivers/chromedriver:$PATH"' >> $GITHUB_ENV
        
    - name: Install environment requirements
      run: pip install -r requirements.txt
      
    - name: Run behave
      run: |
        behave tests -f json -o my_json_output.json
        python report_generation.py --input_json_file  my_json_output.json --output_html_file report.html
        open ./ report.html

      

      
    
    

    
    
     
