name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
      - uses: cryptic-wizard/run-behave-tests@v0.3.0
        with:
          test-path: example_project
          test-output-name: results.txt
          
     
