name: Run Tests

on:
  push

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Chrome
      run: |
        brew reinstall --cask google-chrome
        /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version    
        
    - name: Checkout Chromedriver 
      run: |
          cd webdrivers/mac
          chromeDriver -v   
      
    - name: Add chromedriver to PATH
      run: |
          echo 'export PATH="/webdrivers/chromedriver:$PATH"' >> $GITHUB_ENV
        
    - name: Install environment requirements
      run: pip install -r requirements.txt

    - name: Installing allure
      run: brew install allure
      
    - name: Run behave
      id: features
      run: python runner.py

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
          name: allure-report
          path: allure-results
          
    - name: Check on failures
      if: (${{ steps.features.outcome }} == 'failure')
      run: exit 1
    
 

    
    
     
