name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Install Chrome
      run: |
        brew install --cask google-chrome
        google-chrome --version



      

      
    
    

    
    
     
