name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@v1


    - name: Build and run Docker image
      run: |
          docker build -t selenium-tests .
          docker run -v $PWD:/automation_framework selenium-tests behave tests


      

      
    
    

    
    
     
